FROM python:3.9-slim

WORKDIR /app

# Install required packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the consumer script
COPY  kafka_consumer.py .

# Run the consumer script
CMD ["python", "kafka_consumer.py"]